// <auto-generated />
using System;
using EgeControlWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EgeControlWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260407120000_AddSiteSettingsAndVisitorLogs")]
    partial class AddSiteSettingsAndVisitorLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");
#pragma warning restore 612, 618
        }
    }
}
